# Set default shell
# set -g default-shell /bin/zsh

# Set prefix to Ctrl+Space
set -g prefix C-Space
unbind C-b
unbind C-Left
unbind C-Right

setw -g mode-keys vi
set-option -g status-position top
set-option -g mouse on

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key p paste-buffer
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Bind Leader, C-k to clear screen, which is mapped in Wezterm to cmd-K
# to simulate the behavior of other terminals
is_vim="$HOME/.config/tmux/is-vim.sh"
is_zsh="$HOME/.config/tmux/is-zsh.sh"
not_vim="! $HOME/.config/tmux/is-vim.sh"
bind-key C-k if-shell "$not_vim" "send-keys -R" \; if-shell "$is_zsh" "send-keys C-l" \; clear-history

# Match LazyVim split keys
bind-key - split-window -v
bind-key _ split-window -v
bind-key \| split-window -h

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
# Renumber windows when one is closed
set-option -g renumber-windows on

# List of plugins
# set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'NHDaly/tmux-better-mouse-mode'
set -g @plugin 'rickstaa/tmux-notify'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g status-bg colour234

# Initialize TMUX plugin manager (keep these at the very bottom of tmux.conf)
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
